name: Test job_type comparisons

on:
  workflow_dispatch:
    inputs:
      job_type:
        description: 'Choose the job type to test'
        required: true
        default: value

jobs:
  # 1️⃣ Exact match
  equals_check:
    if: ${{ github.event.inputs.job_type == 'value' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "job_type == 'value' matched."

  # 2️⃣ Sub‑string match (inline steps)
  contains_check:
    if: contains(github.event.inputs.job_type, 'value')
    runs-on: ubuntu-latest
    steps:
      - run: echo "job_type contains 'value'."

  # 3️⃣ Sub‑string match (calls a *reusable* workflow)
  contains_check_reusable:
    if: contains(github.event.inputs.job_type, 'value')
    # same repo ‑> just point at the other file
    uses: testorg755/logopu-test5/.github/workflows/reusable-false.yml@main
    with:
      job_type: ${{ github.event.inputs.job_type }}
