name: Test job_type comparisons

on:
  # Manually trigger the workflow and pass a job_type value from the UI or API
  workflow_dispatch:
    inputs:
      job_type:
        description: 'Choose the job type to test'
        required: true
        default: value

jobs:
  # 1️⃣   Runs only if job_type is exactly "value" (case‑insensitive)
  equals_check:
    if: ${{ github.event.inputs.job_type == 'value' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo when equal
        run: echo "job_type == 'value' matched. Running equals_check job."

  # 2️⃣   Runs if job_type contains "value" anywhere in the string (also case‑insensitive)
  contains_check:
    if: contains(github.event.inputs.job_type, 'value')
    runs-on: ubuntu-latest
    steps:
      - name: Echo when contains
        run: echo "job_type contains 'value'. Running contains_check job."
