name: Repro sparse-checkout persistence
on: { workflow_dispatch: {} }

jobs:
  job_a_sparse:
    name: Job A - enable sparse-checkout
    runs-on: [self-hosted, macOS, sparse-lab]  # your labels
    steps:
      - name: Checkout (sparse)
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          path: persist/sparse-repro
          sparse-checkout: |
            .github
          sparse-checkout-cone-mode: true

      - name: Show state at end of Job A (before post step runs)
        run: |
          cd "$GITHUB_WORKSPACE/persist/sparse-repro"
          echo "A/core.sparseCheckout=$(git config --local --get core.sparseCheckout || echo unset)"
          echo "A/patterns:"
          test -f .git/info/sparse-checkout && cat .git/info/sparse-checkout || echo "(none)"

  job_b_probe_then_checkout:
    name: Job B - probe BEFORE checkout, then plain checkout
    needs: job_a_sparse
    runs-on: [self-hosted, macOS, sparse-lab]  # same runner label
    steps:
      - name: Probe state BEFORE running checkout
        run: |
          DIR="$GITHUB_WORKSPACE/persist/sparse-repro"
          echo "Workspace: $GITHUB_WORKSPACE"
          if [ -d "$DIR/.git" ]; then
            cd "$DIR"
            echo "B-before/core.sparseCheckout=$(git config --local --get core.sparseCheckout || echo unset)"
            echo "B-before/patterns:"
            test -f .git/info/sparse-checkout && cat .git/info/sparse-checkout || echo "(none)"
          else
            echo "Repo dir not found: $DIR"
          fi

      - name: Checkout (non-sparse) into SAME dir
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          path: persist/sparse-repro

      - name: Probe state AFTER checkout
        run: |
          cd "$GITHUB_WORKSPACE/persist/sparse-repro"
          echo "B-after/core.sparseCheckout=$(git config --local --get core.sparseCheckout || echo unset)"
          echo "B-after/patterns:"
          test -f .git/info/sparse-checkout && cat .git/info/sparse-checkout || echo "(none)"
          echo "Visible files:"
          ls -la | sed -n '1,200p'
