name: Repro sparse-checkout persistence
on:
  workflow_dispatch:

jobs:
  job_a_sparse:
    name: Job A - enable sparse-checkout
    runs-on: [self-hosted, linux, sparse-lab]  # use a label tied to exactly one runner
    steps:
      - name: Checkout (sparse)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # optional: put it in a subdir that persists across jobs on self-hosted
          path: persist/sparse-repro
          sparse-checkout: |
            .github
          sparse-checkout-cone-mode: true

      - name: Show sparse state after Job A
        run: |
          cd "$GITHUB_WORKSPACE/persist/sparse-repro"
          echo "core.sparseCheckout=$(git config --local --get core.sparseCheckout || echo unset)"
          echo "patterns:"
          if [ -f .git/info/sparse-checkout ]; then cat .git/info/sparse-checkout; else echo "(none)"; fi
          echo "Top-level files visible:"
          ls -la | sed -n '1,120p'

  job_b_nosparse:
    name: Job B - plain checkout (should NOT be sparse, but will be)
    needs: job_a_sparse
    runs-on: [self-hosted, linux, sparse-lab]  # same label to hit the same machine
    steps:
      - name: Checkout (non-sparse) into the SAME dir
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: persist/sparse-repro

      - name: Inspect state in Job B
        run: |
          cd "$GITHUB_WORKSPACE/persist/sparse-repro"
          echo "core.sparseCheckout=$(git config --local --get core.sparseCheckout || echo unset)"
          echo "patterns:"
          if [ -f .git/info/sparse-checkout ]; then cat .git/info/sparse-checkout; else echo "(none)"; fi
          echo "Visible files (expect to still be sparse):"
          ls -la | sed -n '1,200p'
