name: B after A (success only)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  job_a:
    name: Job A
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sleep 60

  job_b:
    name: Job B (runs only if A succeeded)
    if: ${{ needs.job_a.result != 'success' && success() }}
    needs: job_a
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job B running because Job A succeeded"
